---
- hosts: localhost

  tasks:
    - name: Execute Cloudformation to create webserver stack
      cloudformation:
        stack_name: 'WebserverStack'
        state: present
        region: ap-southeast-2
        template_url: Webserver.template
        #template_url: https://github.com/DJEnterprise/cfn/blob/master/Webserver.template
        
    
