---
- hosts: localhost
  
  vars:
    name2: "Suchi"
  
  vars_files: 
    - vars/default_vars.yml
  
  tasks: 
  - debug: 
      msg: Hello World! This is exciting!

  - shell: |
      hostname
      whoami
    register: res
  - debug:
      var: res
  - shell: 
      pwd
      ls
    register: response
  - debug:
      var: response
  - debug: msg="Hello {{name}} from Ansible"
  - debug: msg="Hello {{name2}} from Ansible"
  - debug: msg="You are under the directory - {{response.stdout_lines[0]}}"

  - shell: |
      aws s3 ls
      echo 'My Name is Dhan'
    register: output
  - debug:
      var: output
  #- debug:
  #    msg: "S3 Bucket Name - {{ item }}"
  #  with_items: 
  #      - cfnbucket
  #      - calypsobucket
  - debug: msg="{{output.stdout_lines}}"
  - debug:
      msg: "S3 Bucket Name - {{ item }}"
    with_items: "{{output.stdout_lines}}"
  - shell: |
      aws ec2 describe-instances --region ap-southeast-2 --filters "Name=tag:Name,Values=Grid" --query 'Reservations[].Instances[].PrivateIpAddress'
    register:  awslist
  
  - debug:
      var: awslist
  - debug:
      msg: "Grid Machines: {{ item }} "
    with_items: "{{awslist.stdout_lines}}"
  - debug: msg="Execution Completed Succesfully"