---
- hosts: localhost
  vars:
  - name: ""
  tasks: 
  - debug: 
      msg: Hello World! This is exciting!

  - shell: |
      hostname
      whoami
    register: res
  - debug:
      var: res
  - shell: |
      pwd
      ls
    register: response
  - debug:
      var: response
  - debug: msg="Hello {{name}} from Ansible"
  - debug: msg="You are under the directory - {{response.stdout_lines}}"
