---
- hosts: localhost
  
  vars_files: 
    - vars/default_vars.yml
  
  vars:
    name2: "Suchi"

  tasks: 
  - debug: 
      msg: Hello World! This is exciting!

  - shell: |
      hostname
      whoami
    register: res
  - debug:
      var: res
  - shell: 
      pwd
      ls
    register: response
  - debug:
      var: response
  - debug: msg="Hello {{name}} from Ansible"
  - debug: msg="Hello {{name2}} from Ansible"
  - debug: msg="You are under the directory - {{response.stdout_lines[0]}}"
