---
- hosts: localhost

  tasks: 
  - debug: 
      msg: Hello World! This is exciting!

  - shell: |
      hostname
      whoami
    register: res
  - debug:
      var: res
  - shell: |
      pwd
      ls
    register: response
  - debug:
      var: response
      