---

  - name: Check all the share drives mounted on app servers
    hosts: app-servers
    vars_files:
      - vars/mount_list.yml

    tasks:
    - shell: |
        hostname
        cd {{item}}
        pwd
      with_items: "{{share_path}}"
      register: output

    - debug:
        var: output

    - debug:
        msg: "Paths Verified : {{item.stdout_lines}}"
      with_items: "{{output.results}}"
      loop_control:
        label: "{{ item.stdout_lines }}"

    - debug:
        msg: "Paths Having Issues: {{item.stderr_lines}}"
      with_items: "{{output.results}}"
      loop_control:
        label: "{{ item.stderr_lines }}"

    - debug: 
        msg: "{{item}}"
      with_items: 
      - "{{output.stdout_lines}}"
      #loop_control:
        #label: "{{ item.stdout_lines }}"