---

  - name: Check all the share drives mounted on app servers
    hosts: app-servers
    vars_files:
      - vars/mount_list.yml

    tasks:
    - shell: |
        hostname
        cd {{item}}
        pwd
      with_items: "{{share_path}}"
      register: output

    - debug:
        var: output